use WAREHOUSE ECOM_DEV_WH;
USE DATABASE SAAS_REVENUE_DB;
CREATE OR REPLACE TABLE GOLD_SCHEMA.DIM_CUSTOMERS (
    CUSTOMER_KEY INT AUTOINCREMENT,   -- Surrogate key
    SUBSCRIBER_ID INT,                -- Natural business key
    COMPANY_NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR,
    REGION VARCHAR,
    SIGNUP_DATE DATE,
    ACCOUNT_STATUS VARCHAR
);
CREATE OR REPLACE TABLE GOLD_SCHEMA.DIM_SUBSCRIPTIONS (
    SUBSCRIPTION_KEY INT AUTOINCREMENT,  -- Surrogate key
    SUBSCRIPTION_ID INT,                 -- Natural business key
    SUBSCRIBER_ID INT,                   -- Link to customer
    SUBSCRIPTION_TIER VARCHAR,
    MRR_VALUE DECIMAL(10,2),
    BILLING_CYCLE VARCHAR,
    SUBSCRIPTION_START_DATE DATE,
    CANCELLATION_DATE DATE
  
);
CREATE OR REPLACE TABLE GOLD_SCHEMA.FACT_SUPPORT_TICKETS (
    TICKET_ID INT,
    SUBSCRIPTION_KEY INT,
    CUSTOMER_KEY INT,                    -- Surrogate FK to DIM_CUSTOMERS
    ISSUE_CATEGORY VARCHAR,
    SEVERITY VARCHAR,
    RESOLUTION_TIME_HOURS DECIMAL(10,2),
    TICKET_DATE DATE
);


