USE DATABASE SAAS_REVENUE_DB;
USE SCHEMA ANALYTICS_SCHEMA;

-- ============================================================
-- Analytics View: VW_EXECUTIVE_SUMMARY
-- Purpose: Top-level KPIs for executive scorecards
-- ============================================================
CREATE OR REPLACE VIEW ANALYTICS_SCHEMA.VW_EXECUTIVE_SUMMARY AS
SELECT 
    COUNT(DISTINCT c.CUSTOMER_KEY) AS TOTAL_CUSTOMERS,
    SUM(CASE WHEN c.ACCOUNT_STATUS = 'Active' THEN 1 ELSE 0 END) AS ACTIVE_CUSTOMERS,
    SUM(CASE WHEN c.ACCOUNT_STATUS = 'Churned' THEN 1 ELSE 0 END) AS CHURNED_CUSTOMERS,
    SUM(s.MRR_VALUE) AS TOTAL_MRR,
    AVG(s.MRR_VALUE) AS AVG_MRR
FROM GOLD_SCHEMA.DIM_CUSTOMERS c
LEFT JOIN GOLD_SCHEMA.DIM_SUBSCRIPTIONS s ON c.SUBSCRIBER_ID = s.SUBSCRIBER_ID;

-- ============================================================
-- Analytics View: VW_REGIONAL_REVENUE
-- Purpose: Track revenue performance and customer counts by region & tier
-- ============================================================
CREATE OR REPLACE VIEW ANALYTICS_SCHEMA.VW_REGIONAL_REVENUE AS
SELECT 
    c.REGION,
    s.SUBSCRIPTION_TIER,
    COUNT(DISTINCT c.CUSTOMER_KEY) AS TOTAL_CUSTOMERS,
    SUM(s.MRR_VALUE) AS REGIONAL_MRR,
    AVG(s.MRR_VALUE) AS AVG_CUSTOMER_MRR
FROM GOLD_SCHEMA.DIM_CUSTOMERS c
JOIN GOLD_SCHEMA.DIM_SUBSCRIPTIONS s ON c.SUBSCRIBER_ID = s.SUBSCRIBER_ID
GROUP BY c.REGION, s.SUBSCRIPTION_TIER;

-- ============================================================
-- Analytics View: VW_CHURN_DRIVERS
-- Purpose: Analyze operational support metrics against account status
-- ============================================================
CREATE OR REPLACE VIEW ANALYTICS_SCHEMA.VW_CHURN_DRIVERS AS
SELECT 
    c.ACCOUNT_STATUS,
    t.ISSUE_CATEGORY,
    t.SEVERITY,
    COUNT(DISTINCT t.TICKET_ID) AS TOTAL_TICKETS,
    AVG(t.RESOLUTION_TIME_HOURS) AS AVG_RESOLUTION_HOURS
FROM GOLD_SCHEMA.DIM_CUSTOMERS c
JOIN GOLD_SCHEMA.FACT_SUPPORT_TICKETS t ON c.CUSTOMER_KEY = t.CUSTOMER_KEY
GROUP BY c.ACCOUNT_STATUS, t.ISSUE_CATEGORY, t.SEVERITY;
