use WAREHOUSE ECOM_DEV_WH;
USE DATABASE SAAS_REVENUE_DB;
TRUNCATE TABLE RAW_SCHEMA.SUBSCRIBERS_RAW;
COPY INTO RAW_SCHEMA.SUBSCRIBERS_RAW
FROM @RAW_SCHEMA.SAAS_RAW_DATA/subscribers_raw.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE';
TRUNCATE TABLE RAW_SCHEMA.SUBSCRIPTIONS_RAW;
COPY INTO RAW_SCHEMA.SUBSCRIPTIONS_RAW
FROM @RAW_SCHEMA.SAAS_RAW_DATA/subscriptions_raw.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE';

TRUNCATE TABLE RAW_SCHEMA.SUPPORT_TICKETS_RAW;
COPY INTO RAW_SCHEMA.SUPPORT_TICKETS_RAW
FROM @RAW_SCHEMA.SAAS_RAW_DATA/support_tickets_raw.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE';